# Generated by Django 4.2.11 on 2024-03-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Введите ФИО')),
                ('profession', models.CharField(max_length=100, verbose_name='Введите полное название должности')),
                ('photo', models.ImageField(upload_to='teachers/')),
            ],
        ),
    ]
