# Generated by Django 4.2.11 on 2024-03-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.CharField(choices=[('Учитель', 'Учитель'), ('Администрация', 'Администрация'), ('Директор', 'Директор')], default=1, max_length=100, verbose_name='Выберите категорию'),
            preserve_default=False,
        ),
    ]
