# Generated by Django 4.2.11 on 2024-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='teachers/', verbose_name='Фото'),
        ),
    ]
