# Generated by Django 4.2.11 on 2024-05-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='schedule',
            field=models.TextField(default='Понедельник: 10:00 - 18:00', verbose_name='Введите график работы'),
            preserve_default=False,
        ),
    ]
